apiVersion: v1
name: opensearchservice-chart
description: A Helm chart for the ACK service controller for Amazon OpenSearch Service (OpenSearch)
version: 1.0.6
appVersion: 1.0.6
home: https://github.com/aws-controllers-k8s/opensearchservice-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/opensearchservice-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: OpenSearch Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/opensearchservice-maintainer
keywords:
  - aws
  - kubernetes
  - opensearchservice
